/* Insertar partidos */
-- Individuales Masculino : Copa de los Mosqueteros
INSERT INTO partido VALUES ('R128IM1',128,'I','M',1);
INSERT INTO partido VALUES ('R128IM2',128,'I','M',2);
INSERT INTO partido VALUES ('R128IM3',128,'I','M',3);
INSERT INTO partido VALUES ('R128IM4',128,'I','M',4);
INSERT INTO partido VALUES ('R128IM5',128,'I','M',5);
INSERT INTO partido VALUES ('R128IM6',128,'I','M',6);
INSERT INTO partido VALUES ('R128IM7',128,'I','M',7);
INSERT INTO partido VALUES ('R128IM8',128,'I','M',8);
INSERT INTO partido VALUES ('R128IM9',128,'I','M',9);
INSERT INTO partido VALUES ('R128IM10',128,'I','M',10);
INSERT INTO partido VALUES ('R128IM11',128,'I','M',11);
INSERT INTO partido VALUES ('R128IM12',128,'I','M',12);
INSERT INTO partido VALUES ('R128IM13',128,'I','M',13);
INSERT INTO partido VALUES ('R128IM14',128,'I','M',14);
INSERT INTO partido VALUES ('R128IM15',128,'I','M',15);
INSERT INTO partido VALUES ('R128IM16',128,'I','M',16);
INSERT INTO partido VALUES ('R128IM17',128,'I','M',17);
INSERT INTO partido VALUES ('R128IM18',128,'I','M',18);
INSERT INTO partido VALUES ('R128IM19',128,'I','M',19);
INSERT INTO partido VALUES ('R128IM20',128,'I','M',20);
INSERT INTO partido VALUES ('R128IM21',128,'I','M',21);
INSERT INTO partido VALUES ('R128IM22',128,'I','M',22);
INSERT INTO partido VALUES ('R128IM23',128,'I','M',23);
INSERT INTO partido VALUES ('R128IM24',128,'I','M',24);
INSERT INTO partido VALUES ('R128IM25',128,'I','M',25);
INSERT INTO partido VALUES ('R128IM26',128,'I','M',26);
INSERT INTO partido VALUES ('R128IM27',128,'I','M',27);
INSERT INTO partido VALUES ('R128IM28',128,'I','M',28);
INSERT INTO partido VALUES ('R128IM29',128,'I','M',29);
INSERT INTO partido VALUES ('R128IM30',128,'I','M',30);
INSERT INTO partido VALUES ('R128IM31',128,'I','M',31);
INSERT INTO partido VALUES ('R128IM32',128,'I','M',32);
INSERT INTO partido VALUES ('R128IM33',128,'I','M',33);
INSERT INTO partido VALUES ('R128IM34',128,'I','M',34);
INSERT INTO partido VALUES ('R128IM35',128,'I','M',35);
INSERT INTO partido VALUES ('R128IM36',128,'I','M',36);
INSERT INTO partido VALUES ('R128IM37',128,'I','M',37);
INSERT INTO partido VALUES ('R128IM38',128,'I','M',38);
INSERT INTO partido VALUES ('R128IM39',128,'I','M',39);
INSERT INTO partido VALUES ('R128IM40',128,'I','M',40);
INSERT INTO partido VALUES ('R128IM41',128,'I','M',41);
INSERT INTO partido VALUES ('R128IM42',128,'I','M',42);
INSERT INTO partido VALUES ('R128IM43',128,'I','M',43);
INSERT INTO partido VALUES ('R128IM44',128,'I','M',44);
INSERT INTO partido VALUES ('R128IM45',128,'I','M',45);
INSERT INTO partido VALUES ('R128IM46',128,'I','M',46);
INSERT INTO partido VALUES ('R128IM47',128,'I','M',47);
INSERT INTO partido VALUES ('R128IM48',128,'I','M',48);
INSERT INTO partido VALUES ('R128IM49',128,'I','M',49);
INSERT INTO partido VALUES ('R128IM50',128,'I','M',50);
INSERT INTO partido VALUES ('R128IM51',128,'I','M',51);
INSERT INTO partido VALUES ('R128IM52',128,'I','M',52);
INSERT INTO partido VALUES ('R128IM53',128,'I','M',53);
INSERT INTO partido VALUES ('R128IM54',128,'I','M',54);
INSERT INTO partido VALUES ('R128IM55',128,'I','M',55);
INSERT INTO partido VALUES ('R128IM56',128,'I','M',56);
INSERT INTO partido VALUES ('R128IM57',128,'I','M',57);
INSERT INTO partido VALUES ('R128IM58',128,'I','M',58);
INSERT INTO partido VALUES ('R128IM59',128,'I','M',59);
INSERT INTO partido VALUES ('R128IM60',128,'I','M',60);
INSERT INTO partido VALUES ('R128IM61',128,'I','M',61);
INSERT INTO partido VALUES ('R128IM62',128,'I','M',62);
INSERT INTO partido VALUES ('R128IM63',128,'I','M',63);
INSERT INTO partido VALUES ('R128IM64',128,'I','M',64);
INSERT INTO partido VALUES ('R64IM1',64,'I','M',1);
INSERT INTO partido VALUES ('R64IM2',64,'I','M',2);
INSERT INTO partido VALUES ('R64IM3',64,'I','M',3);
INSERT INTO partido VALUES ('R64IM4',64,'I','M',4);
INSERT INTO partido VALUES ('R64IM5',64,'I','M',5);
INSERT INTO partido VALUES ('R64IM6',64,'I','M',6);
INSERT INTO partido VALUES ('R64IM7',64,'I','M',7);
INSERT INTO partido VALUES ('R64IM8',64,'I','M',8);
INSERT INTO partido VALUES ('R64IM9',64,'I','M',9);
INSERT INTO partido VALUES ('R64IM10',64,'I','M',10);
INSERT INTO partido VALUES ('R64IM11',64,'I','M',11);
INSERT INTO partido VALUES ('R64IM12',64,'I','M',12);
INSERT INTO partido VALUES ('R64IM13',64,'I','M',13);
INSERT INTO partido VALUES ('R64IM14',64,'I','M',14);
INSERT INTO partido VALUES ('R64IM15',64,'I','M',15);
INSERT INTO partido VALUES ('R64IM16',64,'I','M',16);
INSERT INTO partido VALUES ('R64IM17',64,'I','M',17);
INSERT INTO partido VALUES ('R64IM18',64,'I','M',18);
INSERT INTO partido VALUES ('R64IM19',64,'I','M',19);
INSERT INTO partido VALUES ('R64IM20',64,'I','M',20);
INSERT INTO partido VALUES ('R64IM21',64,'I','M',21);
INSERT INTO partido VALUES ('R64IM22',64,'I','M',22);
INSERT INTO partido VALUES ('R64IM23',64,'I','M',23);
INSERT INTO partido VALUES ('R64IM24',64,'I','M',24);
INSERT INTO partido VALUES ('R64IM25',64,'I','M',25);
INSERT INTO partido VALUES ('R64IM26',64,'I','M',26);
INSERT INTO partido VALUES ('R64IM27',64,'I','M',27);
INSERT INTO partido VALUES ('R64IM28',64,'I','M',28);
INSERT INTO partido VALUES ('R64IM29',64,'I','M',29);
INSERT INTO partido VALUES ('R64IM30',64,'I','M',30);
INSERT INTO partido VALUES ('R64IM31',64,'I','M',31);
INSERT INTO partido VALUES ('R64IM32',64,'I','M',32);
INSERT INTO partido VALUES ('R32IM1',32,'I','M',1);
INSERT INTO partido VALUES ('R32IM2',32,'I','M',2);
INSERT INTO partido VALUES ('R32IM3',32,'I','M',3);
INSERT INTO partido VALUES ('R32IM4',32,'I','M',4);
INSERT INTO partido VALUES ('R32IM5',32,'I','M',5);
INSERT INTO partido VALUES ('R32IM6',32,'I','M',6);
INSERT INTO partido VALUES ('R32IM7',32,'I','M',7);
INSERT INTO partido VALUES ('R32IM8',32,'I','M',8);
INSERT INTO partido VALUES ('R32IM9',32,'I','M',9);
INSERT INTO partido VALUES ('R32IM10',32,'I','M',10);
INSERT INTO partido VALUES ('R32IM11',32,'I','M',11);
INSERT INTO partido VALUES ('R32IM12',32,'I','M',12);
INSERT INTO partido VALUES ('R32IM13',32,'I','M',13);
INSERT INTO partido VALUES ('R32IM14',32,'I','M',14);
INSERT INTO partido VALUES ('R32IM15',32,'I','M',15);
INSERT INTO partido VALUES ('R32IM16',32,'I','M',16);
INSERT INTO partido VALUES ('R16IM1',16,'I','M',1);
INSERT INTO partido VALUES ('R16IM2',16,'I','M',2);
INSERT INTO partido VALUES ('R16IM3',16,'I','M',3);
INSERT INTO partido VALUES ('R16IM4',16,'I','M',4);
INSERT INTO partido VALUES ('R16IM5',16,'I','M',5);
INSERT INTO partido VALUES ('R16IM6',16,'I','M',6);
INSERT INTO partido VALUES ('R16IM7',16,'I','M',7);
INSERT INTO partido VALUES ('R16IM8',16,'I','M',8);
INSERT INTO partido VALUES ('RQFIM1',8,'I','M',1);
INSERT INTO partido VALUES ('RQFIM2',8,'I','M',2);
INSERT INTO partido VALUES ('RQFIM3',8,'I','M',3);
INSERT INTO partido VALUES ('RQFIM4',8,'I','M',4);
INSERT INTO partido VALUES ('RSFIM1',4,'I','M',1);
INSERT INTO partido VALUES ('RSFIM2',4,'I','M',2);
INSERT INTO partido VALUES ('RFIM1',2,'I','M',1);
--Individuales Femenino : Copa Suzanne-Lenglen
INSERT INTO partido VALUES ('R64IF1',64,'I','F',1);
INSERT INTO partido VALUES ('R64IF2',64,'I','F',2);
INSERT INTO partido VALUES ('R64IF3',64,'I','F',3);
INSERT INTO partido VALUES ('R64IF4',64,'I','F',4);
INSERT INTO partido VALUES ('R64IF5',64,'I','F',5);
INSERT INTO partido VALUES ('R64IF6',64,'I','F',6);
INSERT INTO partido VALUES ('R64IF7',64,'I','F',7);
INSERT INTO partido VALUES ('R64IF8',64,'I','F',8);
INSERT INTO partido VALUES ('R64IF9',64,'I','F',9);
INSERT INTO partido VALUES ('R64IF10',64,'I','F',10);
INSERT INTO partido VALUES ('R64IF11',64,'I','F',11);
INSERT INTO partido VALUES ('R64IF12',64,'I','F',12);
INSERT INTO partido VALUES ('R64IF13',64,'I','F',13);
INSERT INTO partido VALUES ('R64IF14',64,'I','F',14);
INSERT INTO partido VALUES ('R64IF15',64,'I','F',15);
INSERT INTO partido VALUES ('R64IF16',64,'I','F',16);
INSERT INTO partido VALUES ('R64IF17',64,'I','F',17);
INSERT INTO partido VALUES ('R64IF18',64,'I','F',18);
INSERT INTO partido VALUES ('R64IF19',64,'I','F',19);
INSERT INTO partido VALUES ('R64IF20',64,'I','F',20);
INSERT INTO partido VALUES ('R64IF21',64,'I','F',21);
INSERT INTO partido VALUES ('R64IF22',64,'I','F',22);
INSERT INTO partido VALUES ('R64IF23',64,'I','F',23);
INSERT INTO partido VALUES ('R64IF24',64,'I','F',24);
INSERT INTO partido VALUES ('R64IF25',64,'I','F',25);
INSERT INTO partido VALUES ('R64IF26',64,'I','F',26);
INSERT INTO partido VALUES ('R64IF27',64,'I','F',27);
INSERT INTO partido VALUES ('R64IF28',64,'I','F',28);
INSERT INTO partido VALUES ('R64IF29',64,'I','F',29);
INSERT INTO partido VALUES ('R64IF30',64,'I','F',30);
INSERT INTO partido VALUES ('R64IF31',64,'I','F',31);
INSERT INTO partido VALUES ('R64IF32',64,'I','F',32);
INSERT INTO partido VALUES ('R32IF1',32,'I','F',1);
INSERT INTO partido VALUES ('R32IF2',32,'I','F',2);
INSERT INTO partido VALUES ('R32IF3',32,'I','F',3);
INSERT INTO partido VALUES ('R32IF4',32,'I','F',4);
INSERT INTO partido VALUES ('R32IF5',32,'I','F',5);
INSERT INTO partido VALUES ('R32IF6',32,'I','F',6);
INSERT INTO partido VALUES ('R32IF7',32,'I','F',7);
INSERT INTO partido VALUES ('R32IF8',32,'I','F',8);
INSERT INTO partido VALUES ('R32IF9',32,'I','F',9);
INSERT INTO partido VALUES ('R32IF10',32,'I','F',10);
INSERT INTO partido VALUES ('R32IF11',32,'I','F',11);
INSERT INTO partido VALUES ('R32IF12',32,'I','F',12);
INSERT INTO partido VALUES ('R32IF13',32,'I','F',13);
INSERT INTO partido VALUES ('R32IF14',32,'I','F',14);
INSERT INTO partido VALUES ('R32IF15',32,'I','F',15);
INSERT INTO partido VALUES ('R32IF16',32,'I','F',16);
INSERT INTO partido VALUES ('R16IF1',16,'I','F',1);
INSERT INTO partido VALUES ('R16IF2',16,'I','F',2);
INSERT INTO partido VALUES ('R16IF3',16,'I','F',3);
INSERT INTO partido VALUES ('R16IF4',16,'I','F',4);
INSERT INTO partido VALUES ('R16IF5',16,'I','F',5);
INSERT INTO partido VALUES ('R16IF6',16,'I','F',6);
INSERT INTO partido VALUES ('R16IF7',16,'I','F',7);
INSERT INTO partido VALUES ('R16IF8',16,'I','F',8);
INSERT INTO partido VALUES ('RQFIF1',8,'I','F',1);
INSERT INTO partido VALUES ('RQFIF2',8,'I','F',2);
INSERT INTO partido VALUES ('RQFIF3',8,'I','F',3);
INSERT INTO partido VALUES ('RQFIF4',8,'I','F',4);
INSERT INTO partido VALUES ('RSFIF1',4,'I','F',1);
INSERT INTO partido VALUES ('RSFIF2',4,'I','F',2);
INSERT INTO partido VALUES ('RFIF1',2,'I','F',1);
-- Dobles Femenino : Copa Simone Mathieu
INSERT INTO partido VALUES ('R64DF1',64,'D','F',1);
INSERT INTO partido VALUES ('R64DF2',64,'D','F',2);
INSERT INTO partido VALUES ('R64DF3',64,'D','F',3);
INSERT INTO partido VALUES ('R64DF4',64,'D','F',4);
INSERT INTO partido VALUES ('R64DF5',64,'D','F',5);
INSERT INTO partido VALUES ('R64DF6',64,'D','F',6);
INSERT INTO partido VALUES ('R64DF7',64,'D','F',7);
INSERT INTO partido VALUES ('R64DF8',64,'D','F',8);
INSERT INTO partido VALUES ('R64DF9',64,'D','F',9);
INSERT INTO partido VALUES ('R64DF10',64,'D','F',10);
INSERT INTO partido VALUES ('R64DF11',64,'D','F',11);
INSERT INTO partido VALUES ('R64DF12',64,'D','F',12);
INSERT INTO partido VALUES ('R64DF13',64,'D','F',13);
INSERT INTO partido VALUES ('R64DF14',64,'D','F',14);
INSERT INTO partido VALUES ('R64DF15',64,'D','F',15);
INSERT INTO partido VALUES ('R64DF16',64,'D','F',16);
INSERT INTO partido VALUES ('R64DF17',64,'D','F',17);
INSERT INTO partido VALUES ('R64DF18',64,'D','F',18);
INSERT INTO partido VALUES ('R64DF19',64,'D','F',19);
INSERT INTO partido VALUES ('R64DF20',64,'D','F',20);
INSERT INTO partido VALUES ('R64DF21',64,'D','F',21);
INSERT INTO partido VALUES ('R64DF22',64,'D','F',22);
INSERT INTO partido VALUES ('R64DF23',64,'D','F',23);
INSERT INTO partido VALUES ('R64DF24',64,'D','F',24);
INSERT INTO partido VALUES ('R64DF25',64,'D','F',25);
INSERT INTO partido VALUES ('R64DF26',64,'D','F',26);
INSERT INTO partido VALUES ('R64DF27',64,'D','F',27);
INSERT INTO partido VALUES ('R64DF28',64,'D','F',28);
INSERT INTO partido VALUES ('R64DF29',64,'D','F',29);
INSERT INTO partido VALUES ('R64DF30',64,'D','F',30);
INSERT INTO partido VALUES ('R64DF31',64,'D','F',31);
INSERT INTO partido VALUES ('R64DF32',64,'D','F',32);
INSERT INTO partido VALUES ('R32DF1',32,'D','F',1);
INSERT INTO partido VALUES ('R32DF2',32,'D','F',2);
INSERT INTO partido VALUES ('R32DF3',32,'D','F',3);
INSERT INTO partido VALUES ('R32DF4',32,'D','F',4);
INSERT INTO partido VALUES ('R32DF5',32,'D','F',5);
INSERT INTO partido VALUES ('R32DF6',32,'D','F',6);
INSERT INTO partido VALUES ('R32DF7',32,'D','F',7);
INSERT INTO partido VALUES ('R32DF8',32,'D','F',8);
INSERT INTO partido VALUES ('R32DF9',32,'D','F',9);
INSERT INTO partido VALUES ('R32DF10',32,'D','F',10);
INSERT INTO partido VALUES ('R32DF11',32,'D','F',11);
INSERT INTO partido VALUES ('R32DF12',32,'D','F',12);
INSERT INTO partido VALUES ('R32DF13',32,'D','F',13);
INSERT INTO partido VALUES ('R32DF14',32,'D','F',14);
INSERT INTO partido VALUES ('R32DF15',32,'D','F',15);
INSERT INTO partido VALUES ('R32DF16',32,'D','F',16);
INSERT INTO partido VALUES ('R16DF1',16,'D','F',1);
INSERT INTO partido VALUES ('R16DF2',16,'D','F',2);
INSERT INTO partido VALUES ('R16DF3',16,'D','F',3);
INSERT INTO partido VALUES ('R16DF4',16,'D','F',4);
INSERT INTO partido VALUES ('R16DF5',16,'D','F',5);
INSERT INTO partido VALUES ('R16DF6',16,'D','F',6);
INSERT INTO partido VALUES ('R16DF7',16,'D','F',7);
INSERT INTO partido VALUES ('R16DF8',16,'D','F',8);
INSERT INTO partido VALUES ('RQFDF1',8,'D','F',1);
INSERT INTO partido VALUES ('RQFDF2',8,'D','F',2);
INSERT INTO partido VALUES ('RQFDF3',8,'D','F',3);
INSERT INTO partido VALUES ('RQFDF4',8,'D','F',4);
INSERT INTO partido VALUES ('RSFDF1',4,'D','F',1);
INSERT INTO partido VALUES ('RSFDF2',4,'D','F',2);
INSERT INTO partido VALUES ('RFDF1',2,'D','F',1);
-- Dobles Masculino : Copa Jacques Brugnon
INSERT INTO partido VALUES ('R64DM1',64,'D','M',1);
INSERT INTO partido VALUES ('R64DM2',64,'D','M',2);
INSERT INTO partido VALUES ('R64DM3',64,'D','M',3);
INSERT INTO partido VALUES ('R64DM4',64,'D','M',4);
INSERT INTO partido VALUES ('R64DM5',64,'D','M',5);
INSERT INTO partido VALUES ('R64DM6',64,'D','M',6);
INSERT INTO partido VALUES ('R64DM7',64,'D','M',7);
INSERT INTO partido VALUES ('R64DM8',64,'D','M',8);
INSERT INTO partido VALUES ('R64DM9',64,'D','M',9);
INSERT INTO partido VALUES ('R64DM10',64,'D','M',10);
INSERT INTO partido VALUES ('R64DM11',64,'D','M',11);
INSERT INTO partido VALUES ('R64DM12',64,'D','M',12);
INSERT INTO partido VALUES ('R64DM13',64,'D','M',13);
INSERT INTO partido VALUES ('R64DM14',64,'D','M',14);
INSERT INTO partido VALUES ('R64DM15',64,'D','M',15);
INSERT INTO partido VALUES ('R64DM16',64,'D','M',16);
INSERT INTO partido VALUES ('R64DM17',64,'D','M',17);
INSERT INTO partido VALUES ('R64DM18',64,'D','M',18);
INSERT INTO partido VALUES ('R64DM19',64,'D','M',19);
INSERT INTO partido VALUES ('R64DM20',64,'D','M',20);
INSERT INTO partido VALUES ('R64DM21',64,'D','M',21);
INSERT INTO partido VALUES ('R64DM22',64,'D','M',22);
INSERT INTO partido VALUES ('R64DM23',64,'D','M',23);
INSERT INTO partido VALUES ('R64DM24',64,'D','M',24);
INSERT INTO partido VALUES ('R64DM25',64,'D','M',25);
INSERT INTO partido VALUES ('R64DM26',64,'D','M',26);
INSERT INTO partido VALUES ('R64DM27',64,'D','M',27);
INSERT INTO partido VALUES ('R64DM28',64,'D','M',28);
INSERT INTO partido VALUES ('R64DM29',64,'D','M',29);
INSERT INTO partido VALUES ('R64DM30',64,'D','M',30);
INSERT INTO partido VALUES ('R64DM31',64,'D','M',31);
INSERT INTO partido VALUES ('R64DM32',64,'D','M',32);
INSERT INTO partido VALUES ('R32DM1',32,'D','M',1);
INSERT INTO partido VALUES ('R32DM2',32,'D','M',2);
INSERT INTO partido VALUES ('R32DM3',32,'D','M',3);
INSERT INTO partido VALUES ('R32DM4',32,'D','M',4);
INSERT INTO partido VALUES ('R32DM5',32,'D','M',5);
INSERT INTO partido VALUES ('R32DM6',32,'D','M',6);
INSERT INTO partido VALUES ('R32DM7',32,'D','M',7);
INSERT INTO partido VALUES ('R32DM8',32,'D','M',8);
INSERT INTO partido VALUES ('R32DM9',32,'D','M',9);
INSERT INTO partido VALUES ('R32DM10',32,'D','M',10);
INSERT INTO partido VALUES ('R32DM11',32,'D','M',11);
INSERT INTO partido VALUES ('R32DM12',32,'D','M',12);
INSERT INTO partido VALUES ('R32DM13',32,'D','M',13);
INSERT INTO partido VALUES ('R32DM14',32,'D','M',14);
INSERT INTO partido VALUES ('R32DM15',32,'D','M',15);
INSERT INTO partido VALUES ('R32DM16',32,'D','M',16);
INSERT INTO partido VALUES ('R16DM1',16,'D','M',1);
INSERT INTO partido VALUES ('R16DM2',16,'D','M',2);
INSERT INTO partido VALUES ('R16DM3',16,'D','M',3);
INSERT INTO partido VALUES ('R16DM4',16,'D','M',4);
INSERT INTO partido VALUES ('R16DM5',16,'D','M',5);
INSERT INTO partido VALUES ('R16DM6',16,'D','M',6);
INSERT INTO partido VALUES ('R16DM7',16,'D','M',7);
INSERT INTO partido VALUES ('R16DM8',16,'D','M',8);
INSERT INTO partido VALUES ('RQFDM1',8,'D','M',1);
INSERT INTO partido VALUES ('RQFDM2',8,'D','M',2);
INSERT INTO partido VALUES ('RQFDM3',8,'D','M',3);
INSERT INTO partido VALUES ('RQFDM4',8,'D','M',4);
INSERT INTO partido VALUES ('RSFDM1',4,'D','M',1);
INSERT INTO partido VALUES ('RSFDM2',4,'D','M',2);
INSERT INTO partido VALUES ('RFDM1',2,'D','M',1);
-- Dobles Mixto : Copa Marcel Bernard
INSERT INTO partido VALUES ('R64DX1',64,'D','X',1);
INSERT INTO partido VALUES ('R64DX2',64,'D','X',2);
INSERT INTO partido VALUES ('R64DX3',64,'D','X',3);
INSERT INTO partido VALUES ('R64DX4',64,'D','X',4);
INSERT INTO partido VALUES ('R64DX5',64,'D','X',5);
INSERT INTO partido VALUES ('R64DX6',64,'D','X',6);
INSERT INTO partido VALUES ('R64DX7',64,'D','X',7);
INSERT INTO partido VALUES ('R64DX8',64,'D','X',8);
INSERT INTO partido VALUES ('R64DX9',64,'D','X',9);
INSERT INTO partido VALUES ('R64DX10',64,'D','X',10);
INSERT INTO partido VALUES ('R64DX11',64,'D','X',11);
INSERT INTO partido VALUES ('R64DX12',64,'D','X',12);
INSERT INTO partido VALUES ('R64DX13',64,'D','X',13);
INSERT INTO partido VALUES ('R64DX14',64,'D','X',14);
INSERT INTO partido VALUES ('R64DX15',64,'D','X',15);
INSERT INTO partido VALUES ('R64DX16',64,'D','X',16);
INSERT INTO partido VALUES ('R64DX17',64,'D','X',17);
INSERT INTO partido VALUES ('R64DX18',64,'D','X',18);
INSERT INTO partido VALUES ('R64DX19',64,'D','X',19);
INSERT INTO partido VALUES ('R64DX20',64,'D','X',20);
INSERT INTO partido VALUES ('R64DX21',64,'D','X',21);
INSERT INTO partido VALUES ('R64DX22',64,'D','X',22);
INSERT INTO partido VALUES ('R64DX23',64,'D','X',23);
INSERT INTO partido VALUES ('R64DX24',64,'D','X',24);
INSERT INTO partido VALUES ('R64DX25',64,'D','X',25);
INSERT INTO partido VALUES ('R64DX26',64,'D','X',26);
INSERT INTO partido VALUES ('R64DX27',64,'D','X',27);
INSERT INTO partido VALUES ('R64DX28',64,'D','X',28);
INSERT INTO partido VALUES ('R64DX29',64,'D','X',29);
INSERT INTO partido VALUES ('R64DX30',64,'D','X',30);
INSERT INTO partido VALUES ('R64DX31',64,'D','X',31);
INSERT INTO partido VALUES ('R64DX32',64,'D','X',32);
INSERT INTO partido VALUES ('R32DX1',32,'D','X',1);
INSERT INTO partido VALUES ('R32DX2',32,'D','X',2);
INSERT INTO partido VALUES ('R32DX3',32,'D','X',3);
INSERT INTO partido VALUES ('R32DX4',32,'D','X',4);
INSERT INTO partido VALUES ('R32DX5',32,'D','X',5);
INSERT INTO partido VALUES ('R32DX6',32,'D','X',6);
INSERT INTO partido VALUES ('R32DX7',32,'D','X',7);
INSERT INTO partido VALUES ('R32DX8',32,'D','X',8);
INSERT INTO partido VALUES ('R32DX9',32,'D','X',9);
INSERT INTO partido VALUES ('R32DX10',32,'D','X',10);
INSERT INTO partido VALUES ('R32DX11',32,'D','X',11);
INSERT INTO partido VALUES ('R32DX12',32,'D','X',12);
INSERT INTO partido VALUES ('R32DX13',32,'D','X',13);
INSERT INTO partido VALUES ('R32DX14',32,'D','X',14);
INSERT INTO partido VALUES ('R32DX15',32,'D','X',15);
INSERT INTO partido VALUES ('R32DX16',32,'D','X',16);
INSERT INTO partido VALUES ('R16DX1',16,'D','X',1);
INSERT INTO partido VALUES ('R16DX2',16,'D','X',2);
INSERT INTO partido VALUES ('R16DX3',16,'D','X',3);
INSERT INTO partido VALUES ('R16DX4',16,'D','X',4);
INSERT INTO partido VALUES ('R16DX5',16,'D','X',5);
INSERT INTO partido VALUES ('R16DX6',16,'D','X',6);
INSERT INTO partido VALUES ('R16DX7',16,'D','X',7);
INSERT INTO partido VALUES ('R16DX8',16,'D','X',8);
INSERT INTO partido VALUES ('RQFDX1',8,'D','X',1);
INSERT INTO partido VALUES ('RQFDX2',8,'D','X',2);
INSERT INTO partido VALUES ('RQFDX3',8,'D','X',3);
INSERT INTO partido VALUES ('RQFDX4',8,'D','X',4);
INSERT INTO partido VALUES ('RSFDX1',4,'D','X',1);
INSERT INTO partido VALUES ('RSFDX2',4,'D','X',2);
INSERT INTO partido VALUES ('RFDX1',2,'D','X',1);
/* INSERTAR Game */
-- Individual Masculino
INSERT INTO game VALUES ('R128IM1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM5',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM6',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM7',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM8',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM9',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM10',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM11',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM12',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM13',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM14',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM15',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM16',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM17',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM18',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM19',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM20',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM21',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM22',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM23',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM24',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM25',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM26',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM27',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM28',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM29',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM30',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM31',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM32',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM33',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM34',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM35',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM36',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM37',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM38',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM39',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM40',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM41',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM42',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM43',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM44',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM45',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM46',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM47',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM48',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM49',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM50',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM51',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM52',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM53',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM54',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM55',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM56',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM57',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM58',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM59',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM60',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM61',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM62',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM63',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R128IM64',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM5',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM6',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM7',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM8',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM9',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM10',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM11',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM12',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM13',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM14',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM15',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM16',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM17',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM18',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM19',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM20',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM21',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM22',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM23',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM24',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM25',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM26',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM27',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM28',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM29',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM30',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM31',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IM32',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IM1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IM2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IM3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IM4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IM5',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IM6',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IM7',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IM8',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IM9',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IM10',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IM11',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IM12',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IM13',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IM14',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IM15',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IM16',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16IM1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16IM2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16IM3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16IM4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16IM5',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16IM6',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16IM7',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16IM8',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFIM1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFIM2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFIM3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFIM4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RSFIM1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RSFIM2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RFIM1',null,null,null,null,null,null,null,null,null,null,null,null);
-- Individual Femenino
INSERT INTO game VALUES ('R64IF1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF5',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF6',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF7',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF8',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF9',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF10',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF11',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF12',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF13',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF14',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF15',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF16',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF17',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF18',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF19',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF20',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF21',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF22',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF23',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF24',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF25',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF26',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF27',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF28',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF29',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF30',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF31',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64IF32',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IF1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IF2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IF3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IF4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IF5',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IF6',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IF7',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IF8',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IF9',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IF10',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IF11',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IF12',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IF13',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IF14',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IF15',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32IF16',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16IF1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16IF2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16IF3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16IF4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16IF5',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16IF6',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16IF7',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16IF8',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFIF1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFIF2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFIF3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFIF4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RSFIF1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RSFIF2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RFIF1',null,null,null,null,null,null,null,null,null,null,null,null);
-- Dobles Femenino
INSERT INTO game VALUES ('R64DF1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF5',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF6',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF7',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF8',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF9',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF10',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF11',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF12',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF13',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF14',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF15',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF16',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF17',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF18',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF19',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF20',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF21',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF22',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF23',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF24',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF25',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF26',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF27',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF28',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF29',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF30',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF31',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DF32',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DF1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DF2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DF3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DF4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DF5',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DF6',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DF7',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DF8',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DF9',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DF10',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DF11',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DF12',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DF13',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DF14',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DF15',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DF16',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DF1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DF2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DF3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DF4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DF5',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DF6',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DF7',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DF8',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFDF1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFDF2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFDF3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFDF4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RSFDF1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RSFDF2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RFDF1',null,null,null,null,null,null,null,null,null,null,null,null);
-- Dobles Masculino
INSERT INTO game VALUES ('R64DM1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM5',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM6',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM7',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM8',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM9',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM10',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM11',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM12',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM13',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM14',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM15',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM16',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM17',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM18',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM19',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM20',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM21',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM22',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM23',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM24',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM25',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM26',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM27',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM28',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM29',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM30',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM31',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DM32',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DM1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DM2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DM3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DM4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DM5',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DM6',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DM7',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DM8',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DM9',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DM10',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DM11',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DM12',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DM13',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DM14',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DM15',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DM16',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DM1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DM2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DM3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DM4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DM5',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DM6',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DM7',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DM8',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFDM1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFDM2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFDM3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFDM4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RSFDM1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RSFDM2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RFDM1',null,null,null,null,null,null,null,null,null,null,null,null);
--Dobles Mixto
INSERT INTO game VALUES ('R64DX1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX5',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX6',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX7',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX8',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX9',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX10',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX11',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX12',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX13',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX14',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX15',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX16',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX17',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX18',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX19',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX20',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX21',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX22',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX23',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX24',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX25',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX26',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX27',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX28',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX29',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX30',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX31',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R64DX32',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DX1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DX2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DX3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DX4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DX5',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DX6',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DX7',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DX8',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DX9',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DMX0',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DX11',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DX12',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DX13',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DX14',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DX15',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R32DX16',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DX1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DX2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DX3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DX4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DX5',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DX6',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DX7',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('R16DX8',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFDX1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFDX2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFDX3',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RQFDX4',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RSFDX1',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RSFDX2',null,null,null,null,null,null,null,null,null,null,null,null);
INSERT INTO game VALUES ('RFDX1',null,null,null,null,null,null,null,null,null,null,null,null);

/* INSERTAR Jurado */
-- Tomado de https://es.wikipedia.org/wiki/Anexo:%C3%81rbitros_de_tenis
INSERT INTO jurado VALUES ('Adel noir','Egipto',2);
INSERT INTO jurado VALUES ('Ali Nili','USA',0);
INSERT INTO jurado VALUES ('Arnaud Gabas','Francia',1);
INSERT INTO jurado VALUES ('Carlos Bernabes','Brasil',2);
INSERT INTO jurado VALUES ('Carlos Ramos','Portugal',2);
INSERT INTO jurado VALUES ('Cédric Mourier','Francia',2);
INSERT INTO jurado VALUES ('Damian Steiner','Argentina',3);
INSERT INTO jurado VALUES ('Damien Dumusois','Francia',3);
INSERT INTO jurado VALUES ('Emmanuel Joseph','Francia',1);
INSERT INTO jurado VALUES ('Felix Torralba','España',2);
INSERT INTO jurado VALUES ('Fergus Murphy','Irlanda',2);
INSERT INTO jurado VALUES ('Gianluca Moscarella','Italia',2);
INSERT INTO jurado VALUES ('Greg Allensworth','USA',2);
INSERT INTO jurado VALUES ('Jake Garner','USA',3);
INSERT INTO jurado VALUES ('James Keothavong','Gran Bretaña',3);
INSERT INTO jurado VALUES ('John Blom','Australia',1);
INSERT INTO jurado VALUES ('Kader Nouni','Francia',2);
INSERT INTO jurado VALUES ('Manuel Messina','Italia',2);
INSERT INTO jurado VALUES ('Mohamed El Jennati','Marruecos',2);
INSERT INTO jurado VALUES ('Mohamed Lahyani','Suecia',2);
INSERT INTO jurado VALUES ('Pascal Maria','Francia',3);
INSERT INTO jurado VALUES ('Pierre Bacchi','Francia',3);
INSERT INTO jurado VALUES ('Renaud Lichtenstein','Francia',1);
INSERT INTO jurado VALUES ('Richard Haigh','Gran Bretaña',2);
INSERT INTO jurado VALUES ('Roland Herfel','Alemania',2);
INSERT INTO jurado VALUES ('Tony Nimmons','USA',2);
INSERT INTO jurado VALUES ('Alison Hughes (née Lang)','Gran Bretaña',2);
INSERT INTO jurado VALUES ('Eva Asderaki-Moore','Grecia',3);
INSERT INTO jurado VALUES ('Juan (Jennifer) Zhang','China',3);
INSERT INTO jurado VALUES ('Louise Engzell','Suecia',1);
INSERT INTO jurado VALUES ('Mariana Alves','Portugal',2);
INSERT INTO jurado VALUES ('Marija Čičak','Croacia',2);
INSERT INTO jurado VALUES ('Marijana Veljovic','Serbia',2);
INSERT INTO jurado VALUES ('Julie Kjendlie','Noruega',2);
INSERT INTO jurado VALUES ('Paula Vieira Souza','Brasil',3);
INSERT INTO jurado VALUES ('Tamara Vrhovec-Wojcik','Croacia',3);

/* Jugadores 2018 */
--Individuales Masculino
INSERT INTO jugador VALUES('Rafael Nadal',2,'M','Manacor,Mallorca,España','Manacor,Mallorca,España',2001,32,85,185,'Z',2,0,null);
INSERT INTO jugador VALUES('Simone Bolelli',162,'M','Montecarlo,Mónaco','Bolonia,Italia',2003,33,83,183,'D',1,0,null);
INSERT INTO jugador VALUES('Alexander Zverev',3,'M','Montecarlo,Mónaco','Hamburgo,Alemania',2013,22,90,198,'D',2,0,null);
INSERT INTO jugador VALUES('Ricardas Berankis',100,'M','Vilna,LTU/Bradenton,FL,US','Vilna,Lituania',2007,28,77,175,'D',2,0,null);
INSERT INTO jugador VALUES('Marin Cilic',11,'M','Montecarlo,Mónaco','Medjugorje,Bosnia Y Herzegovina',2005,30,89,198,'D',2,0,null);
INSERT INTO jugador VALUES('James Duckworth',149,'M','Sydney,Australia','Sydney,Australia',2010,27,82,183,'D',2,0,null);
INSERT INTO jugador VALUES('Grigor Dimitrov',43,'M','Montecarlo,Mónaco','Haskovo,Bulgaria',2008,27,81,191,'D',1,0,null);
INSERT INTO jugador VALUES('Mohamed Safwat',190,'M','Ciaro','El Mansoura',null,28,83,180,'D',2,0,null);
INSERT INTO jugador VALUES('Juan Martin del Potro',9,'M','Tandil,Argentina','Tandil,Argentina',2005,30,97,198,'D',2,0,null);
INSERT INTO jugador VALUES('Nicolas Mahut',249,'M','Boulogne-Bilancourt,Francia','Angers,Francia',2000,37,82,191,'D',1,0,null);
INSERT INTO jugador VALUES('Kevin Anderson',6,'M','Gulf Stream,Florida,USA','Johannesburgo,Sudáfrica',2007,32,94,203,'D',2,0,null);
INSERT INTO jugador VALUES('Paolo Lorenzi',108,'M','Sarasota,FL,USA','Roma,Italia',2003,37,78,183,'D',2,0,null);
INSERT INTO jugador VALUES('Dominic Thiem',5,'M','Lichtenwörth,Austria','Wiener Neustadt,Austria',2011,25,79,185,'D',1,0,null);
INSERT INTO jugador VALUES('Ilya Ivashka',117,'M','Minsk,Belarus','Minsk,Belarus',2013,25,84,193,'D',2,0,null);
INSERT INTO jugador VALUES('David Goffin',22,'M','Monte Carlo,Mónaco','Rocourt,Bélgica',2009,28,70,180,'D',2,0,null);
INSERT INTO jugador VALUES('Robin Haase',64,'M','Turnhout,Bélgica','La Haya,Holanda',2005,32,77,191,'D',2,0,null);
INSERT INTO jugador VALUES('John Isner',10,'M','Dallas,Texas,USA','Greensboro,Carolina del Norte,USA',2007,33,108,208,'D',2,0,null);
INSERT INTO jugador VALUES('Noah Rubin',143,'M','Long Island,NY,USA','Long Island,NY,USA',2015,23,70,175,'D',2,0,null);
INSERT INTO jugador VALUES('Pablo Carreño Busta',29,'M','Barcelona,España','Gijón,España',2009,27,78,188,'D',2,0,null);
INSERT INTO jugador VALUES('Jozef Kovalik',128,'M','Bratislava,Slovakia','Bratislava,Slovakia',2010,26,82,183,'D',2,0,null);
INSERT INTO jugador VALUES('Siego Schwartzman',25,'M','Buenos Aires,Argentina','Buenos Aires,Argentina',2010,26,64,170,'D',2,0,null);
INSERT INTO jugador VALUES('Calvin Hemery',303,'M','Paris,Francia','Les Lilas,Francia',2013,24,83,191,'D',2,0,null);
INSERT INTO jugador VALUES('Sam Querrey',67,'M','Las Vegas,NV,USA','San Francisco,CA,USA',2006,31,95,298,'D',2,0,null);
INSERT INTO jugador VALUES('Frances Tiafoe',30,'M','Orlando,FL,USA','Hyattsville,Maryland,USA',2015,21,86,188,'D',2,0,null);
INSERT INTO jugador VALUES('Roberto Bautista Agut',21,'M','Castellón De La Plana,España','Castellón De La Plana,España',2005,31,75,183,'D',2,0,null);
INSERT INTO jugador VALUES('Denis Istomin',106,'M','Moscú,Rusia','Orenburg,Rusia',2004,32,85,188,'D',2,0,null);
INSERT INTO jugador VALUES('Jurgen Zopp',177,'M','Tallinn,Estonia','Tallinn,Estonia',2008,31,88,191,'D',2,0,null);
INSERT INTO jugador VALUES('Jack Sock',147,'M','Kansas City,Kansas,USA','Lincoln,Nebraska,USA',2011,26,88,191,'D',2,0,null);
INSERT INTO jugador VALUES('Lucas Pouille',32,'M','Dubai,U.A.E','Grande-Synthe,Francia',2012,25,84,185,'D',2,0,null);
INSERT INTO jugador VALUES('Daniil Medvedev',14,'M','Montecarlo,Mónaco','Moscú,Rusia',2014,23,83,198,'D',2,0,null);
INSERT INTO jugador VALUES('Kyle Edmund',23,'M','Nassau,Bahamas','Johannesburgo,Sudáfrica',2012,24,83,188,'D',2,0,null);
INSERT INTO jugador VALUES('Alex de Miñaur',26,'M','Alicante,España','Sydney,Australia',2015,20,69,183,'D',2,0,null);
INSERT INTO jugador VALUES('Jeremy Chardy',42,'M','Londres,Inglaterra','Pau,Francia',2005,32,75,188,'D',2,0,null);
INSERT INTO jugador VALUES('Tomas Berdych',101,'M','Montecarlo,Mónaco','Valasske Mezirici,Rep.Checa',2002,33,91,196,'D',2,0,null);
INSERT INTO jugador VALUES('Fabio Fognini',12,'M','Arma Di Taggia,Italia','San Remo,Italia',2004,31,79,178,'D',2,0,null);
INSERT INTO jugador VALUES('Pablo Andújar',84,'M','Valencia,España','Cuenca,España',2003,33,80,180,'D',2,0,null);
INSERT INTO jugador VALUES('Kei Nishikori',7,'M','Bradenton,FL,USA','Shimane,Japón',2007,29,73,178,'D',2,0,null);
INSERT INTO jugador VALUES('Maxime Janvier',201,'M',null,null,2014,22,80,193,'D',2,0,null);
INSERT INTO jugador VALUES('Novak Djokovic',1,'M','Montecarlo,Mónaco','Belgrado,Serbia',2003,31,77,188,'D',2,0,null);
INSERT INTO jugador VALUES('Rogerio Dustra Silva',163,'M','Santa Barbara D`Oeste,Brasil','Sao Paulo,Brasil',2003,35,73,178,'D',1,0,null);
INSERT INTO jugador VALUES('Borna Coric',15,'M','Dubai,U.A.E','Zagreb,Croacia',2013,22,85,188,'D',2,0,null);
INSERT INTO jugador VALUES('Philipp Kohlschreiber',41,'M','Kitzbühel,Austria','Augsburgo,Alemania',2001,35,70,178,'D',1,0,null);
INSERT INTO jugador VALUES('Guillermo García López',118,'M','La Roda (Albacete),España','La Roda (Albacete),España',2002,35,80,185,'D',1,0,null);
INSERT INTO jugador VALUES('Stan Wawrinka',34,'M','Montecarlo,Mónaco','Lausanna,Suiza',2002,34,81,183,'D',1,0,null);
INSERT INTO jugador VALUES('Denis Shapovalov',20,'M','Nassau,Bahamas','Tel Aviv,Israel',2017,20,75,183,'Z',1,0,null);
INSERT INTO jugador VALUES('John Millman',39,'M','Brisbane,Australia','Brisbane,Australia',2006,29,79,183,'D',2,0,null);
INSERT INTO jugador VALUES('Steve Johnson',60,'M','Redondo Beach,CA,USA','Orange,CA,USA',2012,29,86,188,'D',2,0,null);
INSERT INTO jugador VALUES('Adrian Mannarino',56,'M','Valleta,Malta','Soizy-Sous-Montmorency,Francia',2004,30,79,180,'Z',2,0,null);
INSERT INTO jugador VALUES('Damir Dzumhur',54,'M','Sarajevo,Bosnia And Herzegovina','Sarajevo,Bosnia And Herzegovina',2011,26,68,175,'D',2,0,null);
INSERT INTO jugador VALUES('Denis Kudla',82,'M','Arlington,Virginia,USA','Kiev,Ucrania',2010,26,79,180,'D',2,0,null);
INSERT INTO jugador VALUES('Richard Gasquet',38,'M','Neuchâtel,Suiza','Beziers,Francia',2002,32,79,183,'D',1,0,null);
INSERT INTO jugador VALUES('Andreas Seppi',62,'M','Caldaro,Italia','Bolzano,Italia',2002,35,78,191,'D',2,0,null);
INSERT INTO jugador VALUES('Sergiy Stakhovsky',115,'M','Kharkov,Ucrania','Kiev,Ucrania',2003,33,80,193,'D',1,0,null);
INSERT INTO jugador VALUES('Feliciano López',93,'M','Madrid,España','Toledo,España',1997,37,88,188,'Z',1,0,null);
INSERT INTO jugador VALUES('Ernest Gulbis',78,'M','Jurmala,Letonia','Riga,Letonia',2004,30,85,191,'D',2,0,null);
INSERT INTO jugador VALUES('Gilles Muller',277,'M','Reckange-Sur-Mess,Luxemburgo','Luxemburgo',2001,35,89,193,'Z',2,0,null);
INSERT INTO jugador VALUES('Fernando Verdasco',37,'M','Doha,Qatar','Madrid,España',2001,35,90,188,'Z',2,0,null);
INSERT INTO jugador VALUES('Yoshihito Nishioka',70,'M','Mie,Japón','Mie,Japón',2014,23,64,170,'Z',2,0,null);
INSERT INTO jugador VALUES('Albert Ramos Viñolas',83,'M','Mataró,España','Barcelona,España',2007,31,76,188,'Z',2,0,null);
INSERT INTO jugador VALUES('Mikhail Kukushkin',40,'M','Astana,Kazajistan','Volgogrado,Rusia',2006,31,72,183,'D',2,0,null);
INSERT INTO jugador VALUES('Gael Monfils',19,'M','Suiza','Paris,Francia',2004,32,85,193,'D',2,0,null);
INSERT INTO jugador VALUES('Elliot Benchetrit',264,'M',null,null,2016,20,80,193,'D',2,0,null);
INSERT INTO jugador VALUES('Radu Albot',44,'M','Chisnau,Moldova','Chisnau,Moldova',2008,29,69,175,'D',2,0,null);
INSERT INTO jugador VALUES('Gregoire Barrere',119,'M','Saint Maur Des Fosses','Charenton-Le-Pont,Francia',2012,25,83,183,'D',2,0,null);
INSERT INTO jugador VALUES('Guido Andreozzi',97,'M','Buenos Aires,Argentina','Buenos Aires,Argentina',2010,27,78,183,'D',2,0,null);
INSERT INTO jugador VALUES('Taylor Fritz',58,'M','Palos Verdes,CA,USA','Rancho Santa Fe,CA,USA',2015,21,86,193,'D',2,0,null);
INSERT INTO jugador VALUES('Ruben Bemelmans',166,'M','Maasmechelen,Bélgica','Genk,Bélgica',2006,31,75,183,'Z',2,0,null);
INSERT INTO jugador VALUES('Yuki Bhambri',333,'M','Nueva Deli,India','Nueva Deli,India',2008,26,75,185,'D',2,0,null);
INSERT INTO jugador VALUES('Julien Benneteau',140,'M','Boulogne-Billancourt,Francia','Bourg-En-&Bresse,Francia',2000,38,79,185,'D',2,0,null);
INSERT INTO jugador VALUES('Leonardo Mayer',63,'M','Buenos Aires,Argentina','Corrientes,Argentina',2003,31,80,191,'D',1,0,null);
INSERT INTO jugador VALUES('Matteo Berrettini',55,'M',null,null,2015,23,90,196,'D',2,0,null);
INSERT INTO jugador VALUES('Oscar Otte',146,'M',null,null,2011,25,79,193,'D',2,0,null);
INSERT INTO jugador VALUES('Marco Cecchinato',17,'M','Palermo,Italia','Palermo,Italia',2010,26,78,185,'D',1,0,null);
INSERT INTO jugador VALUES('Marius Copil',80,'M','Arad,Rumania','Arad,Rumania',2008,28,87,193,'D',1,0,null);
INSERT INTO jugador VALUES('Pablo Cuevas',73,'M','Salto,Uruguay','Concordia,Argentina',2004,33,80,180,'D',1,0,null);
INSERT INTO jugador VALUES('Aljaz Bedene',74,'M','Londres,UK','Ljubljana,Eslovenia',2008,29,73,183,'D',2,0,null);
INSERT INTO jugador VALUES('Federico Delbonis',76,'M','Azul,Argentina','Azul,Argentina',2007,28,90,193,'Z',2,0,null);
INSERT INTO jugador VALUES('Thomaz Belluci',212,'M','Sao Paulo,Brasil','Tiete,Brasil',2005,31,82,188,'Z',2,0,null);
INSERT INTO jugador VALUES('Jared Donaldson',232,'M','Irvine,CA,USA','Providence,RI,USA',2014,22,75,188,'D',2,0,null);
INSERT INTO jugador VALUES('Nicolas Jarry',81,'M','Santiago,Chile','Santiago,Chile',2014,23,90,198,'D',2,0,null);
INSERT INTO jugador VALUES('Thomas Fabbiano',91,'M','San Giorgio Jonico,Italia','Grottaglie,Italia',2005,29,69,173,'D',2,0,null);
INSERT INTO jugador VALUES('Matthew Ebden',53,'M','Perth,Australia','Durban,Sudáfrica',2006,31,80,188,'D',2,0,null);
INSERT INTO jugador VALUES('Marton Fucsovics',36,'M','Budapest,Hungria','Nyiregyhaza,Hungria',2010,27,82,188,'D',2,0,null);
INSERT INTO jugador VALUES('Vasek Pospisil',132,'M','Freeport,Bahamas','Vernon,British Columbia',2007,28,88,193,'D',2,0,null);
INSERT INTO jugador VALUES('Santiago Giraldo',202,'M','Pereira,Colombia','Pereira,Colombia',2004,31,75,188,'D',2,0,null);
INSERT INTO jugador VALUES('Marcos Baghdatis',137,'M','Limassol,Chipre','Limassol,Chipre',2003,33,82,178,'D',2,0,null);
INSERT INTO jugador VALUES('Pierre Hugues Herbert',49,'M','Delémont,Suiza','Schiltigheim,Francia',2010,28,75,188,'D',2,0,null);
INSERT INTO jugador VALUES('Peter Polansky',127,'M','Thornhill,Ontaro,Canada','North York,Canada',2007,30,80,183,'D',2,0,null);
INSERT INTO jugador VALUES('Hubert Hurkacz',52,'M','Wroclaw,Poland','Wroclaw,Poland',2015,22,81,196,'D',2,0,null);
INSERT INTO jugador VALUES('Tennys Sandgren',103,'M','Gallatin,TN,USA','Gallatin,TN,USA',2011,27,88,188,'D',2,0,null);
INSERT INTO jugador VALUES('Malek Jaziri',72,'M','Túnez','Bizerta,Túnez',2003,35,81,185,'D',2,0,null);
INSERT INTO jugador VALUES('Mikhail Youzhny',115,'M','Moscú,Rusia','Moscú,Rusia',1999,37,73,183,'D',1,0,null);
INSERT INTO jugador VALUES('Karen Khachanov',13,'M','Dubai,EAU','Moscú,Rusia',2013,22,87,198,'D',2,0,null);
INSERT INTO jugador VALUES('Andreas Haider Maurer',415,'M','Innsbruck,Austria','Zwettl,Austria',2005,32,89,191,'D',2,0,null);
INSERT INTO jugador VALUES('Martin Klizan',47,'M','Bratislava,Eslovaquia','Bratislava,Eslovaquia',2007,29,85,191,'Z',2,0,null);
INSERT INTO jugador VALUES('Laslo Djere',33,'M','Senta,Serbia','Senta,Serbia',2013,23,82,188,'D',2,0,null);
INSERT INTO jugador VALUES('Dusan Lajovic',24,'M','Stara Pazova,Serbia','Belgrado,Serbia',2007,28,83,183,'D',1,0,null);
INSERT INTO jugador VALUES('Jiri Vesely',94,'M','Ras Al Khaimah,UAE','Pribran,Republica Checa',2009,25,94,198,'Z',2,0,null);
INSERT INTO jugador VALUES('Maximilian Marterer',102,'M','Stein Alemania',null,2015,23,84,191,'Z',2,0,null);
INSERT INTO jugador VALUES('Ryan Harrison',111,'M','Austin,TX,USA','Shreveport,Louisiana,USA',2007,26,84,185,'D',2,0,null);
INSERT INTO jugador VALUES('Corentin Moutet',133,'M','Boulogne-Billancourt,Francia','Paris,Francia',2016,20,68,175,'Z',2,0,null);
INSERT INTO jugador VALUES('Ivo Karlovic',95,'M','Gran Bahama','Zagreb,Croacia',2000,40,104,211,'D',1,0,null);
INSERT INTO jugador VALUES('Jaume Munar',57,'M','Santanyi,Mallorca,España','Santanyi,Mallorca,España',2014,21,76,183,'D',2,0,null);
INSERT INTO jugador VALUES('David Ferrer',155,'M','Valencia,España','Jávea,España',2000,37,73,175,'D',2,0,null);
INSERT INTO jugador VALUES('Cameron Norrie',45,'M','Forth Worth,TX,USA','Johannesburgo,Sudáfrica',2017,23,82,188,'Z',2,0,null);
INSERT INTO jugador VALUES('Peter Gojowczyk',85,'M','Munich,Alemania','Dachau,Alemania',2006,29,83,188,'D',2,0,null);
INSERT INTO jugador VALUES('Benoit Paire',46,'M','Ginebra,Suiza','Avignon,Francia',2007,29,80,196,'D',2,0,null);
INSERT INTO jugador VALUES('Roberto Carballés Baena',104,'M','Granada,España','Tenerife,España',2011,26,77,183,'D',2,0,null);
INSERT INTO jugador VALUES('Adam Pavlasek',208,'M','Bilovec,Rep.Checa','Bilovec,Rep.Checa',2012,24,76,185,'D',2,0,null);
INSERT INTO jugador VALUES('Mirza Basic',200,'M',null,null,2012,27,88,188,'D',2,0,null);
INSERT INTO jugador VALUES('Guido Pella',28,'M','Buenos Aires,Argentina','Bahía Blanca,Argentina',2007,28,79,183,'Z',2,0,null);
INSERT INTO jugador VALUES('Joao Souza',50,'M','Barcelona,España','Guimaraes,Portugal',2008,30,74,185,'D',2,0,null);
INSERT INTO jugador VALUES('Gilles Simon',27,'M','Neuchatel,Suiza','Niza,Francia',2002,34,70,183,'D',2,0,null);
INSERT INTO jugador VALUES('Nikoloz Basilashvili',18,'M','Tbilisi,Georgia,USA','Tbilisi,Georgia,USA',2008,27,79,185,'D',2,0,null);
INSERT INTO jugador VALUES('Jan Lennard Struff',51,'M','Warstein,Alemania','Warstein,Alemania',2009,28,92,196,'D',2,0,null);
INSERT INTO jugador VALUES('Evgeny Donskoy',138,'M','Moscú,Rusia','Moscú,Rusia',2007,28,75,185,'D',2,0,null);
INSERT INTO jugador VALUES('Marco Trungelliti',131,'M','Ordino,Andorra','Santiago del Estero,Argentina',2008,29,78,180,'D',2,0,null);
INSERT INTO jugador VALUES('Bernard Tomic',77,'M','Montecarlo,Mónaco','Stuttgart,Alemania',2008,26,91,196,'D',2,0,null);
INSERT INTO jugador VALUES('Stefanos Tsitsipas',8,'M','Nicosia,Grecia','Atenas,Grecia',2016,20,85,193,'D',1,0,null);
INSERT INTO jugador VALUES('Carlos Taberner',283,'M','Valencia,España','Valencia,España',2015,21,78,183,'D',2,0,null);
INSERT INTO jugador VALUES('Elias Ymer',113,'M','Estocolmo,Suecia','Skara,Sweden',2014,23,79,183,'D',2,0,null);
INSERT INTO jugador VALUES('Dudi Sela',235,'M','Tel Aviv,Israel','Kiryat Shmonna,Israel',2002,34,65,175,'D',1,0,null);
INSERT INTO jugador VALUES('Horacio Zeballos',18,'M','Buenos Aires,Argentina','Mar de Plata,Argentina',2003,33,84,188,'Z',1,0,null);
INSERT INTO jugador VALUES('Yuichi Sugita',185,'M','Tokio,Japón','Sendai,Japón',2006,30,72,175,'D',2,0,null);
INSERT INTO jugador VALUES('Mischa Zverek',96,'M','Montecarlo,Mónaco','Moscú,Rusia',2005,31,88,191,'Z',2,0,null);
INSERT INTO jugador VALUES('Ernesto Escobedo',288,'M','West Covina,CA,USA','Los Angeles,CA,USA',2014,22,82,185,'D',2,0,null);
INSERT INTO jugador VALUES('Corentin Denolly',426,'M',null,null,null,21,77,185,'Z',2,0,null);
INSERT INTO jugador VALUES('John Patrick Smith',228,'M','Townsville,Autralia','Townsville,Australia',2012,30,84,188,'Z',2,0,null);
INSERT INTO jugador VALUES('Daniel Elahi Galan',196,'M','Bogota,Colombia','Bucaramanga,Colombia',2015,22,72,191,'D',2,0,null);
